---
title: "PROJECT-1"
author: "zhiwei xiao"
date: "6/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mlb = read.csv("http://www.stat.cmu.edu/cmsac/sure/materials/data/eda_projects/top_hitters_2019_batted_balls.csv")
```


```{r}
library(tidyverse)
library(protoclust)
library(ggthemes)
library(gt)

dim(mlb)
colnames(mlb)
table(mlb$pitch_type)
table(mlb$outcome)
table(mlb$batter_stand)
ggplot(na.omit(mlb)) + geom_point(aes(x = hit_x, y = hit_y, color = player), size = 0.4) + geom_smooth(aes(x = hit_x, y = hit_y)) + facet_wrap(vars(outcome)) + theme_bw()
```

```{r}
mlb %>% group_by(player, outcome) %>% summarize(count = n ()) %>%
  pivot_wider(names_from = outcome, values_from = count) %>% arrange(desc(home_run))
```

```{r}
## heatmap of hit_x vs hit_y
na.omit(mlb) %>% filter(outcome == "single") %>% mutate(hit_x = hit_x/7.5, hit_y = hit_y/7.5) %>%
  ggplot(aes(x = hit_x, y = hit_y)) + 
  stat_density2d(h = 0.7, bins = 20,
                 aes(fill = after_stat(level)),
                 geom = "polygon") +
  scale_fill_gradient(low = "darkblue",
                      high = "darkorange") + 
  theme_bw() + theme(legend.position = "bottom")+
 coord_fixed() + scale_x_continuous(limits = c(-12,12)) + scale_y_continuous(limits = c(-1,20)) +
  labs(title = "Heatmap of Hit Coordinates",
       x = "X Coordinate of Hit", y = "Y Coordinate of Hit")
#ggsave(file="heatmap.pdf")
```





```{r}
ggplot(na.omit(mlb)) + geom_point(aes(x = hit_x, y = hit_y, color = outcome)) + 
  theme_bw() + labs(title = "Hit_X vs. Hit_Y",
       subtitle = "coloring based on outcome")
```

```{r}
hc.complete = hclust(dist(na.omit(select(mlb, hit_x, hit_y,exit_velocity,launch_angle,hit_distance
                                         ))) , method = "complete")
# plot(hc.complete)

c4.complete = cutree(hc.complete, 4)

ggplot(na.omit(mlb)) + geom_point(aes(x = hit_x, y = hit_y, color = factor(c4.complete))) + 
  theme_bw() + labs(color="cluster group", title = "Hit Coordinates Graph",
       subtitle = "based on hierarchical clustering with complete linkage", 
       x = "X Coordinate of Hit", y = "Y Coordinate of Hit") + ggthemes::scale_color_colorblind()
 
```
```{r}

mlb_minimax = protoclust(dist(na.omit(select(mlb, hit_x,   
                                             hit_y,exit_velocity,launch_angle,hit_distance))))
#plot(mlb_minimax)

minimax_mlb_clusters = protocut(mlb_minimax, k = 3)

ggplot(na.omit(mlb)) + geom_point(aes(x = hit_x, y = hit_y, color = factor(minimax_mlb_clusters$cl)))+ theme_bw() + labs(color="cluster group", title = "Hit Coordinates Graph",
       subtitle = "based on hierarchical clustering with minimax linkage", 
       x = "X Coordinate of Hit", y = "Y Coordinate of Hit") + ggthemes::scale_color_colorblind()

```

